### ISSUE TITLE
Typo in reference to "services.js"

### ISSUE THREAD

**Issue by willuhn** [Jerrkawz/HAGearS3#1]
Could you please change "Services.js" to "services.js" in index.html, line 79? The referenced file cannot be loaded otherwise.

https://github.com/Jerrkawz/HAGearS3/blob/28f6b065ee85a8ab91bc35e2600310f4a9da00c2/index.html#L79

**Comment by Jerrkawz** [comment]
Good catch. For some reason in my local repo it was Services.js but git had it as services.js. Fixed
