### ISSUE TITLE
Home hosted webserver

### ISSUE THREAD

**Issue by x12eape12x** [Jerrkawz/HAGearS3#11]
So I run a home hosted webserver that doesn't have a password, when I add the interface into the webserver I can get it to come up but when I try to get it on the gear itself it says error 404 not found. Any tips or suggestions on what to do here? I may have missed something

**Comment by Jerrkawz** [comment]
Still need help? Im missing details. The current version of the app requires the now deprecated api_password to be configured in home assistant.

**Comment by x12eape12x** [comment]
I have not tried it but can I use a he hosted webserver to run this?

**Comment by jerrod-lankford** [comment]
I added token auth to the app. Your server still needs to be accessible outside of your home network though most likely
