### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by brando224** [Jerrkawz/HAGearS3#3]
I don't get the whole URL thing. What URL would I use if I wanted to control my Philips hue?

**Comment by Jerrkawz** [comment]
It’s your home assistant url or up address. Do you have your hue bulbs set up inside of Home assistant ?

**Comment by brando224** [comment]
Thanks for the reply. Yeah they are on Google home. How would I get a URL for that?

**Comment by Jerrkawz** [comment]
Not google home, Home Assistant: https://home-assistant.io/

If you have Home Assistant set up it would be accessible in the browser via some url or IP address, thats the url that you need.

**Comment by brando224** [comment]
Oh whoops. I misunderstood this. Sorry, thought it was referring to Google home.
