### ISSUE TITLE
ssl cert expired

### ISSUE THREAD

**Issue by pbanj** [Jerrkawz/HAGearS3#33]
![image](https://user-images.githubusercontent.com/17306233/197295759-0d373278-9278-4719-9b2a-5a69507496b5.png)

**Comment by BigKoiv** [comment]
Hopefully this gets resolved soon.

**Comment by U2EZNeko** [comment]
Bump, can't link my watch properly.

**Comment by TheOnlineUser** [comment]
Bump. Website is down

**Comment by ppruneau** [comment]
Was suppose to be résolve in 2020 for good.. That's sad :(

**Comment by TheOnlineUser** [comment]
No archive of this tool somewhere? I'd be happy to rehost if I knew
anything about how it works. But I don't know enough to republish this on
another site.

**Comment by jerrod-lankford** [comment]
Sorry all ill try to fix this but the issue is really two fold. One the cert is expired and i could renew it but as of Nov 31 heroku free tier is going away, which is what the site was hosted on. So i need to find another place to host it to avoid paying 10 bucks a month.

**Comment by TheOnlineUser** [comment]
Not sure what security risks there would be but I have web hosting that I
could possibly let you use. Will get back to you

**Comment by TheOnlineUser** [comment]
Do you need access to cPanel or databases?
https://www.hostgator.com/help/article/can-i-host-friends If not, and if
you could basically clone your files and let me upload them, I could
probably create a new subdomain section on my HostGator site and give you
the info to point your domain name at my servers. But I'd rather not share
cPanel access directly as that gives access to other sites of mine.

**Comment by pbanj** [comment]
I'm willing to buy you the one website package from https://stacksocial.com/sales/ibrave-cloud-startup-web-hosting-lifetime-subscription

It's shared hosting so you can't use su or apt. Not sure what all you need to get it up and running, but if it would work let me know

**Comment by TheOnlineUser** [comment]
Looks like only 9 hours left on the deal (as of 5:45pm Eastern US Time) to
get that package at $25, but I would be happy to chip in some money toward
that too if it would work. But yeah not sure what limits are on that vs
your needs.

**Comment by pbanj** [comment]
The deal never really expires. They just put a timer to make people panic buy. Ive had the hosting for a year ish now. I use it to host a meme website and email as it gives me unlimited emails.

**Comment by TheOnlineUser** [comment]
Wow okay good to know. Well I'm happy to chip in on that $25 cost too if
Jerrod goes for it.

**Comment by svptje** [comment]
How about Let's Encrypt certificates?

**Comment by pbanj** [comment]
Ssl certs isn't an issue. That's super simple to handle. The main issue is his host running out.

**Comment by HeroYui** [comment]
The Oracle Cloud free tier would give you a whole VPS. Maybe this is what you are looking for? [https://www.oracle.com/cloud/free/](https://www.oracle.com/cloud/free/)

**Comment by jerrod-lankford** [comment]
Alright should be good to go. Shoutout to railway.app!
