### ISSUE TITLE
The hassgalaxy.app/[code] URL doesn't do anything for me. What am I missing?

### ISSUE THREAD

**Issue by TheOnlineUser** [Jerrkawz/HAGearS3#34]
1. I install the app and disable Bluetooth then enable WiFi (instructions don't say it needs to be the same Wifi network as your Google Home or as your computer so I assume that doesn't matter, but I have tried it where the watch and computer are on the same wifi network to no avail), but I have also tried with Bluetooth *and* WiFi on and no difference.
2. Open the app on my watch
3. Type in the https://hassgalaxy.app/[specific URL] on my computer
4. It just says "No connection for [code]. Did you type the code correctly? Also make sure your watch is connected to the internet and try again."

I've uninstalled and reinstalled the app a few times to no avail. Can't really get further if that first step isn't working, and not sure what else needs to be different to make it work. Watch is on an internet-connected Wifi.

**Comment by cdfasnacht** [comment]
How was this completed? I'm running into the same issue. I'm not sure what the unique URL at hassgalaxy.app is. I don't see it appear in the watch app, which is where I expect to see it.
