### ISSUE TITLE
Filter is not defined

### ISSUE THREAD

**Issue by klaszlo8207** [Jerrkawz/HAGearS3#4]
Keep saying this error in the console when running it in the emulator

**Comment by klaszlo8207** [comment]
"file:///js/pages/EntitiesPage.js (68) :Uncaught TypeError: Cannot read property 'filter' of undefined"

**Comment by jerrod-lankford** [comment]
That should only happen if the list of entities reported by HA is empty. And there is supposedly ways to configure visual studio to work for development but I've never bothered to try it
