### ISSUE TITLE
New Authentication Methods

### ISSUE THREAD

**Issue by jgrob1** [Jerrkawz/HAGearS3#6]
This app is absolutely brilliant and really useful.  Works perfectly at the moment but... Do you have any plans to update it with the new HA auth methods?

**Comment by Jerrkawz** [comment]
Im a little out of touch with home assistant currently. What new auth methods?

**Comment by jgrob1** [comment]
Thanks for getting back to me. And thanks again for your app.

So they I have just implemented a user based login system (https://www.home-assistant.io/docs/authentication/). While the "legacy" API password still works for now I can imagine that it wont forever and I was just checking whether you had plans to keep up development.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by jacques24681** [comment]
I've just added a username input field to the setup form so it will access HA with the new login. forked this project @ https://github.com/jacques24681/HAGearS3.  I just dont know if I can upload it to the samsung apps store?

**Comment by Jerrkawz** [comment]
Hi, thanks that's awesome. What happens if you dont use the username field? Will it still work with just the old api password? Also you can just issue a pull request and I can merge and redeploy

**Comment by jacques24681** [comment]
Hi Thanks for your great work on this app, I've tried it but it doesn't want to authenticate without a username.  I'll issue a pull request.

**Comment by manuel983** [comment]
is it possible to have the modified apk? I'm not very experienced, I downloaded the code and Tizen Studio but I can not fill it out

**Comment by derekgdicamillo** [comment]
I downloaded the one from app store doesnt have username field. Can I ask how to install from the github zip? I would love to add this to my phone.

**Comment by starkillerOG** [comment]
@jacques24681 would be awesom if you could make the PR in order to get the new autentication in the samsung app store.

**Comment by foldingarmchair** [comment]
i installes the app onto the watch but am using user authentication in hass.  Any chance it can be added?  I'd need to supply a username and password.

Thanks

**Comment by overb1** [comment]
I got the same problem with new Auth system, possible to update the apk on galaxy store?

**Comment by mclaudiopt** [comment]
hello to all. i am just requested to enter a password. is there anyway to enter the username also so that i can login to my system? 
thanks

**Comment by kriss1427** [comment]
Any idea if the updated app with the option to include username will be available in the Samsung store?

**Comment by sclub** [comment]
Using username and password is not the prefered way to use third party applications with Home assistant. The prefered way is to use a long lived access token. Unfortunately the token is so long that is does not make sense to enter it using the watch.
I've added a way to paste it shortly to cl1pr.net and then retrieve it from there to get access.
Is anyone interested in doing a short beta test and give feedback afterwards?

**Comment by jgrob1** [comment]
Have you rewritten the App already. Keen to know more. Do you have a working Beta for testing already?



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by sclub** [comment]
Yes, I forked the project and already did the necessary changes. Beta Samsung app is deployed, I just need E-Mails of beta testers to add them.

**Comment by dclobato** [comment]
@sclub me :)

**Comment by Jerrkawz** [comment]
@sclub Thats great. You should submit a pr and I can merge and replace my version in the app store with yours

**Comment by sclub** [comment]
@Jerrkawz Great, had the feeling that you were not actively maintaining the project. But if you deploy a new version, thats even better. Pull request is already waiting for you :)

**Comment by SamKr** [comment]
That sounds great, looking forward to the new version. If you need beta testers, I'm up for it.

**Comment by sclub** [comment]
@Jerrkawz Did you had some time to check the merge request? I have a version for release in the samsung store ready, but don't want to interfer if you release it anyway.

**Comment by SamKr** [comment]
I'd really appreciate it if a release (of either version) could be pushed to the store. Waiting for this to start using it, since enabling legacy login isn't an option in my setup :(

**Comment by SamKr** [comment]
@sclub, could you please release yours?

**Comment by cwi-vvatsos** [comment]
@Jerrkawz Any change of merging the pr and pushing this to the store? thanks

**Comment by SamKr** [comment]
Guessing this is dead in the water?

**Comment by Aygotori** [comment]
@Jerrkawz @sclub  Do you have the new version of this app? Thanks ^^

**Comment by pinonpierre** [comment]
@Jerrkawz it works now! Thanks!
