### ISSUE TITLE
App has stopped working

### ISSUE THREAD

**Issue by jgrob1** [Jerrkawz/HAGearS3#9]
Hi,  me again.

it's not working at all anymore. I have tried an uninstall / reinstall, still not working. seems to connect, but when I open any categories no devices show, but worse, the app only fills half the screen; likes its all shifted upwards. It's odd.

**Comment by Jerrkawz** [comment]
Seems to work fine for me. Are you using the api_password you set in home assistant config?

**Comment by jgrob1** [comment]
Yes, and this is all I am getting:

[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by monchi59** [comment]
Same problem here. Login seems to work as there is no error code. Just a quick loading time and then nothing listed in the different parts.

It's the first time I try to get it running though.

**Comment by kennethpangky** [comment]
Works for me. First time setup, 2 days ago.

**Comment by Jerrkawz** [comment]
More info required
